name: Test this action
on:
  pull_request:
  push:
    branches-ignore:
    - v1
    tags-ignore:
    - '*'
    paths-ignore:
    - README.md
  workflow_dispatch:
permissions:
  contents: read

jobs:
  testWinRubyPlatformOverride:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        override: [ none, default ]
    name: "Test input win-ruby-platform-override: ${{ matrix.override }}"

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          ruby-version: '2.7's
          win-ruby-platform-override: ${{ matrix.override }}
          bundler: none
      - name: C:/msys64/mingw64/bin/gcc.exe not installed
        run: ruby -e "File.exist?('C:/msys64/mingw64/bin/gcc.exe') && exit!(1)"

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - run: yarn install
    - run: yarn run package
    - name: Check generated files are up to date
      run: git diff --exit-code
